name: Deploy AWS Serverless
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # https://github.blog/changelog/2022-01-13-github-actions-update-on-oidc-based-deployments-to-aws/
      # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect
      # https://github.com/aws-actions/configure-aws-credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::047980477351:role/prdFxReportGithubWorkflow
          aws-region: ap-northeast-1

      - name: install serverlss v3
        run: npm install -g serverless@3.12.0

      - name: install packages
        run: yarn install

      - name: check lint
        run: yarn run lint

      - name: build
        run: yarn run build

      - name: deploy 
        env:
          SLS_STAGE: ${{secrets.SLS_STAGE}}
        run: sls deploy --stage $SLS_STAGE
